### ISSUE TITLE
Add support for setting a different focus keyword per language.

### ISSUE THREAD

**Issue by atimmer** [Yoast/t3ext-yoast-seo#10]
Because the focus keyword is just inserted without taking into account the different language variations of a page, the same focus keyword is used for all variations. The user should be able to set a focus keyword per language variation.

**Comment by omarreiss** [comment]
@haassie can you figure out why this issue has a `needs-testing` label? I don't see a PR that is linked to this.

**Comment by haassie** [comment]
This issue is already fixed
