### ISSUE TITLE
Use proper RequireJS module to integrate with existing TYPO3 backend components

### ISSUE THREAD

**Issue by arnoschoon** [Yoast/t3ext-yoast-seo#12]
In order to be able to properly solve the following issues we need to use a RequireJS module which can interact with other TYPO3 interface components.
- https://github.com/Yoast/t3ext-yoast-seo/issues/1
- https://github.com/Yoast/t3ext-yoast-seo/issues/2
- https://github.com/Yoast/t3ext-yoast-seo/issues/3

The core API of yoast-seo should be exposed using a [RequireJS shim](http://requirejs.org/docs/api.html#config-shim) so it can be used transparently by the aforementioned module.

**Comment by arnoschoon** [comment]
This should also fix the outcome of #8 where the labels `Readability` and `SEO` are not properly translated since they're hardcoded into the template.

**Comment by omarreiss** [comment]
@arnoschoon you labeled this `needs-code-review` but I don't see a PR that is linked to this.

**Comment by omarreiss** [comment]
@haassie can you find out what's the status of this? It seems you got it working without. Is this required for 1.0? If not, please move the milestone or close this issue.

**Comment by haassie** [comment]
This is already done
