### ISSUE TITLE
Length bar always blue in Chrome

### ISSUE THREAD

**Issue by monbauza** [Yoast/t3ext-yoast-seo#22]
The bar colour for the tilte and the meta description should change (to orange or green) based on the number of characters entered. In Chrome, the bar is always blue-coloured. 

![image](https://cloud.githubusercontent.com/assets/9658774/21082127/eb16dd9e-bfd4-11e6-8745-f23d6c6f6594.png)

**Comment by omarreiss** [comment]
If you need any feedback or help on this, @atimmer should be able to point you in the right direction.

**Comment by omarreiss** [comment]
In theory this could be a YoastSEO.js issue. @atimmer what do you think?

**Comment by atimmer** [comment]
Tentatively, I would say that we are either relying on WordPress styles that aren't present in a TYPO3 environment. Or, TYPO3 has styles that break the styles in YoastSEO.js. Or, in the TYPO3 module we aren't including all the necessary YoastSEO.js styles.

I would have to dive into this to confirm this.
