### ISSUE TITLE
Slug is not saved

### ISSUE THREAD

**Issue by monbauza** [Yoast/t3ext-yoast-seo#24]
Slug field shows empty after filling in a slug and refreshing the page

**Comment by omarreiss** [comment]
It's no longer possible to alter the slug using the snippet editor, so the UX is no longer broken. I am moving this to the 1.1 milestone since I think it could still be useful to have this functionality after all.

**Comment by haassie** [comment]
I think the slug functionality will be taken care of in #31. And I think this issue can be closed. What do you think @omarreiss ?
