### ISSUE TITLE
Error in links assessment

### ISSUE THREAD

**Issue by monbauza** [Yoast/t3ext-yoast-seo#27]
The SEO analysis shows the error below when the text contains a link.

- An error occurred in the 'textCompetingLinks' assessment
- An error occurred in the 'textLinks' assessment

Text example

`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis eros tortor, ornare tincidunt lectus feugiat eget. Praesent sagittis mauris et diam aliquam <a href="https://yoast.com/" title="my link">nec pulvinar purus</a>`

![image](https://cloud.githubusercontent.com/assets/9658774/21082522/541e1e94-bfdd-11e6-99cd-9ef9628ec293.png)

**Comment by omarreiss** [comment]
@atimmer might be able to assist here.

**Comment by atimmer** [comment]
This should be retested with the latest version of YoastSEO.js.

**Comment by atimmer** [comment]
So this isn't fixed in the latest version. To be able to debug this we need the value of the text in the `Paper`. This can be retrieved by using `app.paper.getText()`. Then we can verify that this is a YoastSEO.js issue.

**Comment by haassie** [comment]
The `app.paper.getText()` returns the correct text as far as I can see. My console returns an error `punycode.toASCII is not a function`. Is this a missing dependency?
