### ISSUE TITLE
Changing title in snippet editor should change page path indication

### ISSUE THREAD

**Issue by atimmer** [Yoast/t3ext-yoast-seo#3]
Currently, when changing the title in the snippet editor the page path indication still shows the old title. It should display the updated title.

`ieuws` is the title here:
<img width="335" alt="screen shot 2016-08-11 at 12 19 35" src="https://cloud.githubusercontent.com/assets/584693/17585767/e2de46ac-5fbd-11e6-8c28-44d8ca4a9e82.png">

**Comment by arnoschoon** [comment]
Currently this part of the TYPO3 CMS UI isn't integrated whit the rest. If you edit the title of the page with the inline option TYPO3 offers the path segment isn't modified. This seems to be a missing feature in TYPO3 Core so until that is resolved I'm moving this issue to the backlog.

**Comment by haassie** [comment]
This can be closed because in the new UI you can't change the title in the snippetpreview in the page module anymore. In the new TYPO3 backend module, the page path isn't shown that way.
