### ISSUE TITLE
Metadescription doesn't get printed on the frontend

### ISSUE THREAD

**Issue by omarreiss** [Yoast/t3ext-yoast-seo#36]
<img width="912" alt="typo3_cms_demo__typo3_cms_7_6_13_" src="https://cloud.githubusercontent.com/assets/1488816/23025093/f83b4df4-f45c-11e6-9127-0afc2bccd726.png">

<img width="1277" alt="view-source_typo3-demo_maxserv_com_index_php_id_19" src="https://cloud.githubusercontent.com/assets/1488816/23030698/d0e16ed4-f46e-11e6-8281-4529069fa1f6.png">

**Comment by haassie** [comment]
Dit staat nu op de demo omgeving ter test
