### ISSUE TITLE
Autofill FB + Twitter

### ISSUE THREAD

**Issue by maix4648** [Yoast/t3ext-yoast-seo#43]
Twitter Bug
1. Twitter title -  insert some text
2. Twitter description - is emtpy

Result of page: twitter title and description is filled with text of title.

Facebook OK
1. Facebook title -  insert some text
2. Facebook description - is emtpy

Result of page: show only title.

Maybe it will be better empty description autofill with main decription of page.

**Comment by haassie** [comment]
Please review with latest master version. Will be released to demo-environment next week.
