### ISSUE TITLE
Add support for multisites installations

### ISSUE THREAD

**Issue by AlexPixelant** [Yoast/t3ext-yoast-seo#50]
If editor is logged in under one domain (domain1.com) he/she cannot use Yoast extension on other sites within same installation. Error message appears:
"Loading the page content preview failed
404 Not Found"
JS uses origin domain (domain1.com) as Request URL in $.get() function, instead correct one.

**Comment by rmeeuwissen** [comment]
Hi Alex, you are right. A main selling point for TYPO3 is it's multi-site capabilities. We will consider this additional feature for the next 1.1 release.

**Comment by AlexPixelant** [comment]
Hi Ronald,
Do you have a solution for this? If not, we can try to add this possibility and make a pull request.

**Comment by haassie** [comment]
Hi @AlexPixelant. You are always welcome to make patch and a pull request! Our main focus is now on solving some other issues, but if you can try to make a solution we would love to check and implement that!

**Comment by rmeeuwissen** [comment]
Great @AlexPixelant We would love to welcome your contribution.

**Comment by haassie** [comment]
Hi @ABooooo this is already working. For support, you can contact us on Slack
